import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit + GoldRush Kit Demo App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit & @covalenthq/goldrush-kit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="https://github.com/covalenthq/goldrush-kit">GoldRush Kit</a> Demo!
        </h1>
        <div className={styles.container}>
          <ConnectButton.Custom>
            {({ account, openAccountModal, openConnectModal, openChainModal }) => {
              if (!account) {
                return (
                  <div className={styles.buttonContainer}>
                    <button onClick={openConnectModal} className={styles.button}>
                      <span>Connect Wallet</span>
                    </button>

                  </div>
                );
              }
              return (
                <div className={styles.buttonContainer}>
                  <button onClick={openAccountModal} className={`${styles.button} ${styles.greyButton}`} disabled={!account}>
                    Account Details
                  </button>
                  <button onClick={openChainModal} className={`${styles.button} ${styles.greyButton}`} disabled={!account}>
                    Switch Network
                  </button>
                  <button
                    onClick={() => router.push(`/landing?address=${account.address}`)}
                    className={`${styles.button} ${styles.exploreWalletButton}`}
                  >
                    Explore Wallet
                  </button>
                  <div className={styles.addressContainer}>
                    <h3>Address</h3>
                    <p>{account.address}</p>
                  </div>
                </div>
              );
            }}
          </ConnectButton.Custom>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈 & <img style={{display: "inline", width: 24, height: 24}} src="https://www.datocms-assets.com/86369/1670008339-covalent_logomark_three-color.png" />
        </a>
      </footer>
    </div>
  );
};

export default Home;
